import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "../components/header";
import Footer from "@/components/footer";
import localFont from "next/font/local";

const beniFont = localFont({ src: "./fonts/BeniRegular.woff2" });

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${beniFont.className} bg-black`}>
        {/* <div className="container m-auto flex-1 relative"> */}
        <Header />
        {children}
        <Footer />
        {/* </div> */}
      </body>
    </html>
  );
}
